### ISSUE TITLE
Link to dataset in the Locak PySpark Notebook example is broken

### ISSUE THREAD

**Issue by aarora79** [aws-samples/sagemaker-studio-emr#31]
The link [s3a://nyc-tlc/trip data/fhvhv_tripdata_2019-02.csv](s3a://nyc-tlc/trip data/fhvhv_tripdata_2019-02.csv) in [local-pyspark-smstudio.ipynb](https://github.com/aws-samples/sagemaker-studio-emr/blob/main/interactive_notebooks/local-pyspark-smstudio.ipynb) is broken, the CSV file is no longer available. Use parquet instead. The following code snippet works.
```
parquet_df = spark.read.parquet(
    "s3a://nyc-tlc/trip data/fhvhv_tripdata_2019-02.parquet",
    header=True
)
parquet_df.show()
```

**Comment by seanpmorgan** [comment]
Thank you for reporting! Would you like to submit a pull request with a fix? In either case we'll fix this

**Comment by aarora79** [comment]
Sure, would be happy to submit a PR. Will do so today.

**Comment by aarora79** [comment]
just submitted a PR.
